<?php

namespace BO\OccasionBundle\Repository;

/**
 * accountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accountRepository extends \Doctrine\ORM\EntityRepository
{
}
