<?php

namespace BO\OccasionBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAdvert()
    {
        /*$qb = $this
          ->createQueryBuilder('a');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;*/

        return $this
        ->createQueryBuilder('a')
        ->getQuery()
        ->getResult()  ;
    }
    
    public function myAdvert($id)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
        ->innerJoin('a.categories', 'c')
        ->addSelect('c')
        ;
        $qb->where($qb->expr()->in('a.id', $id));
        /*return $qb
        ->getQuery()
        ->getResult()
        ;*/
        return $qb->getSingleResult();
    }
    
    public function getAdvertWithUser($id)

    {
        $qb = $this
          ->createQueryBuilder('a')
          ->leftJoin('a.customer', 'c')
          ->addSelect('c')
          ->where('c.id=:id') 
          ->setParameter('id', $id)
        ;
        return $qb
          ->getQuery()
          //->getResult()
          ->getOneOrNullResult()
        ;
    }

    public function getAdvertForCategory($category)

    {
        switch ($category) { 
        case 'mobiles' : $category=1; 
         break; 
        case 'electromenagers' : $category=2; 
         break; 
        case 'cuisine' : $category=3; 
         break; 
        case 'loisirs' : $category=4; 
         break;
        case 'vetements' : $category=5; 
         break; 
        case 'jardin' : $category=6; 
         break; 
        case 'autres' : $category=7; 
         break; 
        case 'meubles' : $category=8;
         break;
        case 'beaute' : $category=9; 
         break; 
        case 'bebe' : $category=10;
         break;             
        }
        return  $this->createQueryBuilder('a')
        ->leftjoin('a.customer', 'cus')
        ->leftJoin('a.category', 'cat')       
        ->addSelect('cus')
        ->addSelect('cat')
        ->where('a.category = :category')
        ->setParameter('category', $category)
        ->getQuery()
        ->getResult();
    }
    
    public function oneAdvert($id)
    {
        return  $this->createQueryBuilder('a')
        ->leftjoin('a.customer', 'cus')
        ->leftJoin('a.category', 'cat')       
        ->addSelect('cus')
        ->addSelect('cat')
        ->where('a.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getSingleResult();
    }

    public function updateNbView($id)
    {
        return $this->createQueryBuilder('a')
            ->update()
            ->set('a.nbview', 'a.nbview+1')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult();
    }
    
}
