<?php

namespace BO\OccasionBundle\Repository;

/**
 * GovernateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GovernateRepository extends \Doctrine\ORM\EntityRepository
{
}
