<?php

namespace BO\OccasionBundle\Repository;

/**
 * pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pictureRepository extends \Doctrine\ORM\EntityRepository
{
}
