#bo_occasion_homepage:
#    path:     /
#    defaults: { _controller: BOOccasionBundle:Default:index }

bo_occasion_home:
    path:      /{page}
    defaults:
        _controller: BOOccasionBundle:Advert:index
        page:        1
    requirements:
        page: \d*


#bo_occasion_show:
#    path:      /advert/{id}
#    defaults:  { _controller: BOOccasionBundle:Advert:show }
#    requirements:
#        id: \d+

bo_occasion_show:
    path:      /category/show/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:show }
    requirements:
        id: \d+

bo_occasion_add:
    path:      /add
    defaults:  { _controller: BOOccasionBundle:Advert:add }


bo_occasion_edit:
    path:      /edit/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:edit }
    requirements:
        id: \d+

bo_occasion_update:
    path:      /update/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:update }
    requirements:
        id: \d+


bo_occasion_delete:
    path:      /delete/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:delete }
    requirements:
        id: \d+
        
bo_occasion_howitworks:
    path:      /howitworks
    defaults:  { _controller: BOOccasionBundle:Static:howitworks }
    
        
bo_occasion_contact:
    path:      /contact
    defaults:  { _controller: BOOccasionBundle:Advert:contact }
    
bo_occasion_terms:
    path:      /terms
    defaults:  { _controller: BOOccasionBundle:Static:terms }
    
bo_occasion_mobileapp:
    path:      /mobileapp
    defaults:  { _controller: BOOccasionBundle:Static:mobileapp }
    
bo_occasion_privacy:
    path:      /privacy
    defaults:  { _controller: BOOccasionBundle:Static:privacy }
    
bo_occasion_error:
    path:      /error
    defaults:  { _controller: BOOccasionBundle:Static:error }
    
bo_occasion_feedback:
    path:      /feedback
    defaults:  { _controller: BOOccasionBundle:Static:feedback }
    
#bo_occasion_login:
#    path:      /login
#    defaults:  { _controller: BOOccasionBundle:Advert:login }
    
bo_occasion_register:
    path:      /register
    defaults:  { _controller: BOOccasionBundle:Advert:register }
    
bo_occasion_category:
    path:      /category/{category}
    defaults:  { _controller: BOOccasionBundle:Advert:category }    
    
bo_occasion_removeadd:
    path:      /removeadd/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:removeadd }
    requirements:
        id: \d+
bo_occasion_mylist:
    path:      /mylist/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:mylist }     
    
#*****
bo_occasion_readmsg:
    path:      /readmsg/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:readmsg }
    requirements:
        id: \d+

bo_occasion_addmsg:
    path:      /addmsg
    defaults:  { _controller: BOOccasionBundle:Advert:addmsg     }

bo_occasion_deletemsg:
    path:      /deletemsg/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:deletemsg }
    requirements:
        id: \d+

bo_occasion_listmsg:
    path:      /listmsg/{id}
    defaults:  { _controller: BOOccasionBundle:Advert:listmsg }
    requirements:
        id: \d+        